### ISSUE TITLE
Display a message when filtering yields no results

### ISSUE THREAD

**Issue by yatil** [w3c/wai-wcag-quickref#152]
Suggested by @dboudreau.

**Comment by dboudreau** [comment]
More specifically, when no SC are selected, the query still goes through and we can't really tell whats going on - no apparent changes appear on the main pane, regardless of the filters defined. We probably should have an error message whenever there isn't at least one level of SC selected as part of the filtering. Because everything in the quickref starts from the Success Criteria.

**Comment by yatil** [comment]
@dboudreau What do you mean with SC selected? You cannot select SCs, only tags and filters.

**Comment by dboudreau** [comment]
Sorry, I meant the conformance level (A, AA, or AAA).

**Comment by yatil** [comment]
Ah, thanks, @dboudreau!  That makes sense!
