### ISSUE TITLE
Firefox: Sticky parts are jumping around a little bit

### ISSUE THREAD

**Issue by yatil** [w3c/wai-wcag-quickref#176]
See: https://twitter.com/simevidas/status/1043867733346185216

**Comment by stephaniehobson** [comment]
In Firefox you might be able to avoid the JS all together an just use `position: sticky`.

**Comment by yatil** [comment]
/me whispers to @stephaniehobson that this was not a thing when I built it :-D

**Comment by simevidas** [comment]
I tested a bit with CSS `position: sticky` in Firefox. It works really well: the elements stick perfectly without jumping around.

I did this:

1. I disabled JavaScript via Firefox’s Developer Tools.  
2. I added `position: sticky` to the two `.fixedsticky` elements: (1) the `<div>` inside the `#sidebar` element, and (2) the `.navrow` element (the first `<div>` inside `<main>`).

The result: https://www.youtube.com/watch?v=D6NItm179Gw

**Comment by yatil** [comment]
@simevidas Thanks, that is what we do for Webkit/Blink browsers: 

https://github.com/w3c/wai-wcag-quickref/blob/gh-pages/_scss/styles.scss#L16
https://github.com/w3c/wai-wcag-quickref/blob/gh-pages/_js/fixedsticky.jquery.js

**Comment by MarjaE2** [comment]
> position: sticky

Position: sticky is a migraine trigger. In my experience, first, it's used to animate objects, such as sticky headers which change size, when users try to scroll, second, it results in extra animated scrolling, and third, it moves the boundary between scrolling text and the non-scrolling header closer to the middle of the screen. It can also screw with page down.

I don't know what the indetended behavior is.

Of course trying to read Twitter conversations is also a migraine trigger, because of the sheer effect between the series of messages, which scrolls, and the background on either side, which does not scroll, the boundary between these is right near the middle of the screen, and the boundary often cuts across visual elements.
