### ISSUE TITLE
tagging success criteria

### ISSUE THREAD

**Issue by yatil** [w3c/wai-wcag-quickref#28]
## Info

This is a collection of “tagged” WCAG 2.0 Success Critera. Those [tags](https://en.wikipedia.org/wiki/Tag_%28metadata%29) are the broad categories of the success criterion and will be the foundation of the [new quick reference (prototype)](http://w3c.github.io/wai-wcag-quickref/). The aim is to have as few tags as possible and as many as necessary. Theoretically, individual success criteria could go without a tag. See also this view with [tags by success criterion](tags by sc).
### `images`
- 1.1.1 Non-text Content
- 1.2.8 Media Alternative (Prerecorded)
- 1.4.5 Images of Text
- 1.4.9 Images of Text (No Exception)
### `video`
- 1.1.1 Non-text Content
- 1.2.1 Audio-only and Video-only (Prerecorded)
- 1.2.2 Captions (Prerecorded)
- 1.2.3 Audio Description or Media Alternative (Prerecorded)
- 1.2.4 Captions (Live)
- 1.2.5 Audio Description (Prerecorded)
- 1.2.6 Sign Language (Prerecorded)
- 1.2.7 Extended Audio Description (Prerecorded)
- 1.2.8 Media Alternative (Prerecorded)
- 1.4.2 Audio Control
### `audio`
- 1.1.1 Non-text Content
- 1.2.1 Audio-only and Video-only (Prerecorded)
- 1.2.6 Sign Language (Prerecorded)
- 1.2.8 Media Alternative (Prerecorded)
- 1.2.9 Audio-only (Live)
- 1.4.2 Audio Control
- 1.4.7 Low or No Background Audio
### `captions`
- 1.2.2 Captions (Prerecorded)
- 1.2.4 Captions (Live)
### `live`
- 1.2.4 Captions (Live)
- 1.2.9 Audio-only (Live)
### `structure`
- 1.3.1 Info and Relationships
- 1.3.2 Meaningful Sequence
- 1.3.3 Sensory Characteristics
- 1.4.8 Visual Presentation
- 2.1.2 No Keyboard Trap
- 2.4.1 Bypass Blocks
- 2.4.2 Page Titled
- 2.4.3 Focus Order
- 2.4.8 Location
- 2.4.10 Section Headings
### `keyboard`
- 1.3.2 Meaningful Sequence
- 2.1.1 Keyboard
- 2.1.2 No Keyboard Trap
- 2.1.3 Keyboard (No Exception)
- 2.4.3 Focus Order
### `color`
- 1.4.1 Use of Color
- 1.4.3 Contrast (Minimum)
- 1.4.6 Contrast (Enhanced)
### `contrast`
- 1.4.1 Use of Color
- 1.4.3 Contrast (Minimum)
- 1.4.6 Contrast (Enhanced)
### `autoplay`
- 1.4.2 Audio Control
- 2.2.2 Pause, Stop, Hide
- 2.3.1 Three Flashes or Below Threshold
- 2.3.2 Three Flashes
### `control`
- 1.4.2 Audio Control
- 2.2.1 Timing Adjustable
- 2.2.2 Pause, Stop, Hide
- 2.2.4 Interruptions
- 3.2.5 Change on Request
### `text`
- 1.4.4 Resize text
- 1.4.5 Images of Text
- 1.4.8 Visual Presentation
- 1.4.9 Images of Text (No Exception)
### `layout`
- 1.3.1 Info and Relationships
- 1.3.2 Meaningful Sequence
- 1.4.8 Visual Presentation
### `time`
- 2.2.1 Timing Adjustable
- 2.2.2 Pause, Stop, Hide
- 2.2.3 No Timing
- 2.2.4 Interruptions
- 2.2.5 Re-authenticating
### `flashes`
- 2.3.1 Three Flashes or Below Threshold
- 2.3.2 Three Flashes
### `navigation`
- 2.4.1 Bypass Blocks
- 2.4.4 Link Purpose (In Context)
- 2.4.5 Multiple Ways
- 2.4.8 Location
- 2.4.9 Link Purpose (Link Only)
- 3.2.1 On Focus
- 3.2.2 On Input
- 3.2.3 Consistent Navigation
### `focus`
- 2.4.3 Focus Order
- 2.4.7 Focus Visible
- 3.2.1 On Focus
### `links`
- 2.4.4 Link Purpose (In Context)
- 2.4.9 Link Purpose (Link Only)
### `labels`
- 2.4.6 Headings and Labels
- 3.3.2 Labels or Instructions
### `headings`
- 2.4.6 Headings and Labels
- 2.4.10 Section Headings
### `language`
- 3.1.1 Language of Page
- 3.1.2 Language of Parts
- 3.1.5 Reading Level
### `clarification`
- 3.1.3 Unusual Words
- 3.1.4 Abbreviations
- 3.1.5 Reading Level
- 3.1.6 Pronunciation
### `consistency`
- 3.2.3 Consistent Navigation
- 3.2.4 Consistent Identification
- 3.2.5 Change on Request
### `errors`
- 3.3.1 Error Identification
- 3.3.3 Error Suggestion
- 3.3.4 Error Prevention (Legal, Financial, Data)
- 3.3.5 Help
- 3.3.6 Error Prevention (All)
### `compatibility`
- 4.1.1 Parsing
- 4.1.2 Name, Role, Value

**Comment by Ryladog** [comment]
For AUDIO wouldn’t you want to include 1.4.2?

1.4.2 Audio Control: If any audio on a Web page plays automatically for more than 3 seconds, either a  http://www.w3.org/TR/WCAG20/#mechanismdef mechanism is available to pause or stop the audio, or a mechanism is available to control audio volume independently from the overall system volume level. (Level A)

[Shortened the quoted mail from comment – Eric.]

**Comment by yatil** [comment]
Thanks @Ryladog, I will include 1.4.2 to audio (and also to video as most videos have audio).

**Comment by Ryladog** [comment]
Bingo!

Thanks!

**Comment by James-Green** [comment]
I'd suggest adding these to **Layout** as they also relate to how and where we place info on the screen.
- 1.3.1 Info and Relationships
- 1.3.2 Meaningful Sequence

I'd prefer to merge **Color** and **Contrast** but see why you did 2 since you are keeping the tags to 1 word...

I'd maybe add the following to **Control**:
- 2.2.1 Timing Adjustable
- 2.2.4 Interruptions
- 3.2.5 Change on Request

I'm not sure _3.2.5 Change on Request_ needs to be under **Links**

I'd delete **Reading** since it only has one SC and put that one (_3.1.5 Reading Level_) under **Language**

**Comment by yatil** [comment]
I have adopted the suggestions above. Also I removed the `title` tag that had “2.4.2 Page Titled” as the sole SC.

**Comment by davidberman** [comment]
- current wording/code: heading "time"
- suggested revision: heading "timing"
- rationale: "time" is not as clear... "timing" is more aligned with wcag 2.0 language

**Comment by davidberman** [comment]
- current wording/code: heading "clarification"
- suggested revision: heading "clarity"
- rationale: clearer! ... and more what clear writing experts would choose

**Comment by yatil** [comment]
Thanks @davidberman, I think that those are good proposals :-)

**Comment by davidberman** [comment]
:)

On Tue, Oct 6, 2015 at 10:00 AM, Eric Eggert notifications@github.com
wrote:

> Thanks @davidberman https://github.com/davidberman, I think that those
> are good proposals :-)
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/w3c/wai-wcag-quickref/issues/28#issuecomment-145864801
> .

## 

David Berman, RGD, FGDC
David Berman Communications | berman@davidberman.com | @davidberman | blog
http://www.designedgecanada.com/author/david-berman
+1-613-728-6777 | 340 Selby Avenue, Ottawa K2A 3X6

High Level Advisor, United Nations | GDC ethics chair | Ico-D

## Sustainability chair | Carleton University Access Network chair

_Accessibility courses:_ Ottawa | Europe | Vancouver | Victoria
_Upcoming:_ Dublin | Toronto | Mexico City | Cyprus | Bahrain
Watch David on CBS
http://www.wtoc.com/story/17588481/scad-plans-revitalization | Do Good
book news:  http://www.dogoodbook.com/ http://www.dogoodbook.com/"Don't
just do good design ... do good!"

This message may contain proprietary information. Unauthorized
disclosure/copying/distribution of contents prohibited.

**Comment by iadawn** [comment]
A suggestion I would like to throw into the tagging discussion, is to tag based on activity as well as on functional component. This is done in the [Web Accessibility Wizard](http://www.accessiq.org/web-accessibility-wizard) from AccessiQ and I started doing it when I was exploring the Getting Started Tips. I did an [Analysis of SC](https://www.w3.org/WAI/EO/wiki/Quick_Start_Guides/Analysis_of_Success_Criteria) based on the audiences for the Getting started guides which included 'visual designers', 'ux designers', 'content managers', and 'front-end developers'. There were a few other audiences defined, but these core ones were most easily used for classification of WCAG SC purposes.

The value of this is that it makes WCAG more managable for a broader audience as they can focus in on what is relevant to them. Also, for some audiences, functional component language may hide important SC that they need to consider. A prime example is 1.1.1. For someone who is writing copy, would they know that this SC applied to them? Would they select the 'image' tag? Probably not on both counts.

More generally, I wonder if the tags selected are too low level for practical purposes. They seem to concentrate on the thing, e.g. image, or focus, or structure. In terms of information architecture there is nothing wrong with that, I just wonder if we are missing an oppotunity to take it a level higher, and try to use the tags to highlight the theme. For example, instead of talking about 'contrast' we could be talking about 'visibility'. This then encompases contrast, keyboard focus, and, perhaps, font size. Or, when considering 'errors' we could be talking about 'feedback' or 'forms'. The former incorporates instructions as well as error messaging. The latter creates quite a strong grouping of things that need to be considered together.

Finally, I wonder if some of the tags may be a little obscure. In particular:
- 'live'
- 'keyboard' - what about the keyboard?
- 'autoplay'
- 'layout' could be equally 'structure' - how are they different?
- 'time'
- 'focus' - significance or relevance may not be appreciated
- 'clarification' - is simply not clear (sorry ;))

Minor:
- 1.4.8 could arguably be classified within 'control' as it includes a note regarding user selection of color.

**Comment by davidberman** [comment]
I think the tags by activity approach is a brilliant idea, and could ALSO be linked to our tips that classified already by people's role. And so this would allow us to push people to the quickref from the other resources, based on their self-identification.

**Comment by yatil** [comment]
Thanks for the feedback, @iadawn.

The activity-based tagging was discussed before but discarded as the scoping is difficult. I see some advantages to the approach, for example that it is easy for users to identify themselves. On the other hand, it is hard to include as users could have the impression that the resulting success criteria are the only SCs they need to care.

I see that this applies to writers that don’t know that they need to care about 1.1.1 – but then I don’t think you will cover all disciplines. What if a project manager looks at this and doesn’t see his tag: Doesn’t that implicit mean that they don’t need to do anything for accessibility? And even if the select “content writers”, there might be success criteria that apply to them indirectly.

As for your not on the tags proposal: Are those all where you want to see a discussion on? And if yes, do you have an alternative suggestion for those? (It’s OK if you have not.)

**Comment by sharronrush** [comment]
current :  heading "keyboard"
suggested addition: 2.4.7 Focus Visible
rationale: directly related

Current: heading "links"
suggested addition: 4.1.2 Name, Role, Value
rationale: this is relevant to how links are named

PS : +1 for some activities-based tagging.
And a question: will there be an option, as there is in the <a href="http://www.w3.org/WAI/ER/tools/">Evaluation Tools List</a> to add filters?

**Comment by sharronrush** [comment]
current : heading "video"
suggested addition: 2.1.1 Keyboard and 2.1.2 No Keyboard Trap
rationale: often overlooked and critically important

**Comment by melodyma** [comment]
"Captions" and "Live" can be placed within video or audio. People might get it confused with image captions too. 
"Contrast" can co in "Color"
"Autoplay" in "Video"
"Control" in "Video"
"Layout" and "Structure" can be merged
"Headings" seem to be repeat of "Layout", "Structure" and "Navigation"
"Clarification" could be "Content" since clarification is a bit obscure without context
"Consistency" and "Compatibility" are also obscure labels without context

**Comment by sharronrush** [comment]
Agree that clarity, consistency, and compatibility are not likely to be tags that would be understood or helpful.

I feel pretty strongly that color and contrast should be kept separate especially because there are SCs specific to each. Someone could choose the "contrast" tag without needing to know about use of color alone as an indicator. 

Do we have any record of how people configured the current QuickRef? That might be helpful. Or what they search WCAG for?

**Comment by davidberman** [comment]
Regarding including the Use Of Color SC as part of the discussion of Contrast,
it makes sense because of the portion of the Use Of Color SC that refers to the contrast ratio of link text lettering  to surrounding lettering.

On 2015-10-12 16:14, sharronrush wrote:

> Agree that clarity, consistency, and compatibility are not likely to be tags that would be understood or helpful.
> 
> I feel pretty strongly that color and contrast should be kept separate especially because there are SCs specific to each. Someone could choose the "contrast" tag without needing to know about use of color alone as an indicator.
> 
> Do we have any record of how people configured the current QuickRef? That might be helpful. Or what they search WCAG for?
> 
> —
> Reply to this email directly or view it on GitHub https://github.com/w3c/wai-wcag-quickref/issues/28#issuecomment-147524687.

## 

David Berman, RGD, FGDC LinkedIn http://www.linkedin.com/in/bermandavid Twitter @davidberman http://www.twitter.com/davidberman Facebook http://www.facebook.com/davidbberman Skype davidberman.com skype:davidberman.com?chat Google Plus 
https://plus.google.com/u/0/+DavidBermanCom/posts
David Berman Communications | berman@davidberman.com | @davidberman | blog http://www.designedgecanada.com/author/david-berman
+1-613-728-6777 | 340 Selby Avenue, Ottawa K2A 3X6

## High Level Advisor, United Nations | GDC ethics chair | Ico-D Sustainability chair | Carleton University Access Network chair

/Accessibility courses:/ Vancouver | Victoria | Europe | Ottawa
/Upcoming:/ Dublin | Toronto | Mexico City | Cyprus | Bahrain
Watch David on CBS http://www.wtoc.com/story/17588481/scad-plans-revitalization | Do Good book news: http://www.dogoodbook.com/ "Don't just do good design ... do good!"

This message may contain proprietary information. Unauthorized disclosure/copying/distribution of contents prohibited.

**Comment by bakkenb** [comment]
I am on the fence about activity based tags. I would like to see what those proposed tag titles would be so that I could understand the separation between the SC tags and the Activity-based tags. Would it confuse users if they were both included, or Kevin, are you suggesting they would replace the existing list of tags altogether? 

On another note, I have no issue with the addition of the SC to the tags that people have identified on this issue thread. I would however recommend being critical on which tags should be grouped together. The point of the tags is to single out very specific SC about a very specific topic.

**Comment by davidberman** [comment]
+1 for adding filters ... perhaps adding filters for activities would be an even better solution than adding tags for activities,
as it would allow audience members to first identify what hat they are wearing (activity), and then also optional use tags to explore a specific topic.
The filtering is likely more user-friendly than the tagging.

On 2015-10-12 11:40, sharronrush wrote:

> current : heading "keyboard"
> suggested addition: 2.4.7 Focus Visible
> rationale: directly related
> 
> Current: heading "links"
> suggested addition: 4.1.2 Name, Role, Value
> rationale: this is relevant to how links are named
> 
> PS : +1 for some activities-based tagging.
> And a question: will there be an option, as there is in the Evaluation Tools List http://www.w3.org/WAI/ER/tools/ to add filters?
> 
> —
> Reply to this email directly or view it on GitHub https://github.com/w3c/wai-wcag-quickref/issues/28#issuecomment-147456653.

## 

David Berman, RGD, FGDC LinkedIn http://www.linkedin.com/in/bermandavid Twitter @davidberman http://www.twitter.com/davidberman Facebook http://www.facebook.com/davidbberman Skype davidberman.com skype:davidberman.com?chat Google Plus 
https://plus.google.com/u/0/+DavidBermanCom/posts
David Berman Communications | berman@davidberman.com | @davidberman | blog http://www.designedgecanada.com/author/david-berman
+1-613-728-6777 | 340 Selby Avenue, Ottawa K2A 3X6

## High Level Advisor, United Nations | GDC ethics chair | Ico-D Sustainability chair | Carleton University Access Network chair

/Accessibility courses:/ Vancouver | Victoria | Europe | Ottawa
/Upcoming:/ Dublin | Toronto | Mexico City | Cyprus | Bahrain
Watch David on CBS http://www.wtoc.com/story/17588481/scad-plans-revitalization | Do Good book news: http://www.dogoodbook.com/ "Don't just do good design ... do good!"

This message may contain proprietary information. Unauthorized disclosure/copying/distribution of contents prohibited.

**Comment by vmmiller** [comment]
Love the tag approach.  
- I stumble over "clarification", "consistency" and "compatibility".  Don't think these are too intuitive.  
- Not sure that "live" is too intuitive either.
- Suggest making "Control" plural.

**Comment by yatil** [comment]
@sharronrush:

> And a question: will there be an option, as there is in the Evaluation Tools List to add filters?

We don’t plan for that just now, as every additional filter would need to go through the groups. Of course if someone opens an issue to add a filter, they are welcome to do so.

> Do we have any record of how people configured the current QuickRef? That might be helpful. Or what they search WCAG for?

No, we don’t track any information in those regards.

**Comment by yatil** [comment]
Update as a result of the survey:

## Tags

### `images`
- 1.1.1 Non-text Content
- 1.2.8 Media Alternative (Prerecorded)
- 1.4.5 Images of Text
- 1.4.9 Images of Text (No Exception)

### `video`
- 1.1.1 Non-text Content
- 1.2.1 Audio-only and Video-only (Prerecorded)
- 1.2.2 Captions (Prerecorded)
- 1.2.3 Audio Description or Media Alternative (Prerecorded)
- 1.2.4 Captions (Live)
- 1.2.5 Audio Description (Prerecorded)
- 1.2.6 Sign Language (Prerecorded)
- 1.2.7 Extended Audio Description (Prerecorded)
- 1.2.8 Media Alternative (Prerecorded)
- 1.4.2 Audio Control
- 2.1.1 Keyboard
- 2.1.2 No Keyboard Trap

### `audio`
- 1.1.1 Non-text Content
- 1.2.1 Audio-only and Video-only (Prerecorded)
- 1.2.6 Sign Language (Prerecorded)
- 1.2.8 Media Alternative (Prerecorded)
- 1.2.9 Audio-only (Live)
- 1.4.2 Audio Control
- 1.4.7 Low or No Background Audio

### `captions`
- 1.2.2 Captions (Prerecorded)
- 1.2.4 Captions (Live)

### `live`
- 1.2.4 Captions (Live)
- 1.2.9 Audio-only (Live)

### `structure`
- 1.3.1 Info and Relationships
- 1.3.2 Meaningful Sequence
- 1.3.3 Sensory Characteristics
- 1.4.8 Visual Presentation
- 2.1.2 No Keyboard Trap
- 2.4.1 Bypass Blocks
- 2.4.2 Page Titled
- 2.4.3 Focus Order
- 2.4.8 Location
- 2.4.10 Section Headings
- 3.2.3 Consistent Navigation
- 3.2.4 Consistent Identification
- 3.2.5 Change on Request

### `keyboard`
- 1.3.2 Meaningful Sequence
- 2.1.1 Keyboard
- 2.1.2 No Keyboard Trap
- 2.1.3 Keyboard (No Exception)
- 2.4.3 Focus Order
- 2.4.7 Focus Visible

### `color`
- 1.4.1 Use of Color
- 1.4.3 Contrast (Minimum)
- 1.4.6 Contrast (Enhanced)

### `contrast`
- 1.4.1 Use of Color
- 1.4.3 Contrast (Minimum)
- 1.4.6 Contrast (Enhanced)

### `autoplay`
- 1.4.2 Audio Control
- 2.2.2 Pause, Stop, Hide
- 2.3.1 Three Flashes or Below Threshold
- 2.3.2 Three Flashes

### `controls`
- 1.4.2 Audio Control
- 1.4.8 Visual Presentation
- 2.2.1 Timing Adjustable
- 2.2.2 Pause, Stop, Hide
- 2.2.4 Interruptions
- 3.2.5 Change on Request

### `text`
- 1.4.4 Resize text
- 1.4.5 Images of Text
- 1.4.8 Visual Presentation
- 1.4.9 Images of Text (No Exception)

### `layout`
- 1.3.1 Info and Relationships
- 1.3.2 Meaningful Sequence
- 1.4.8 Visual Presentation
- 3.2.3 Consistent Navigation
- 3.2.4 Consistent Identification

### `timing`
- 2.2.1 Timing Adjustable
- 2.2.2 Pause, Stop, Hide
- 2.2.3 No Timing
- 2.2.4 Interruptions
- 2.2.5 Re-authenticating

### `flashes`
- 2.3.1 Three Flashes or Below Threshold
- 2.3.2 Three Flashes

### `navigation`
- 2.4.1 Bypass Blocks
- 2.4.4 Link Purpose (In Context)
- 2.4.5 Multiple Ways
- 2.4.8 Location
- 2.4.9 Link Purpose (Link Only)
- 3.2.1 On Focus
- 3.2.2 On Input
- 3.2.3 Consistent Navigation

### `focus`
- 2.4.3 Focus Order
- 2.4.7 Focus Visible
- 3.2.1 On Focus

### `links`
- 2.4.4 Link Purpose (In Context)
- 2.4.9 Link Purpose (Link Only)
- 4.1.2 Name, Role, Value

### `labels`
- 2.4.6 Headings and Labels
- 3.3.2 Labels or Instructions

### `headings`
- 2.4.6 Headings and Labels
- 2.4.10 Section Headings

### `language`
- 3.1.1 Language of Page
- 3.1.2 Language of Parts
- 3.1.5 Reading Level

### `content`
- 3.1.3 Unusual Words
- 3.1.4 Abbreviations
- 3.1.5 Reading Level
- 3.1.6 Pronunciation

### `errors`
- 3.3.1 Error Identification
- 3.3.3 Error Suggestion
- 3.3.4 Error Prevention (Legal, Financial, Data)
- 3.3.5 Help
- 3.3.6 Error Prevention (All)

### `compatibility`
- 4.1.1 Parsing
- 4.1.2 Name, Role, Value

**Comment by yatil** [comment]
@melodyma 

> "Captions" and "Live" can be placed within video or audio. People might get it confused with image captions too. 
> "Autoplay" in "Video"
> "Control" in "Video"

I’m not in favor of lumping all of those together, as some of them are special cases. `Controls` also applies to audio and other interactive elements, `autoplay` SCs also to certain CSS animations. They are also special cases of video (when used in the video context), so I think it is better to keep it separate.

> "Contrast" can co in "Color"

This is more an UI decision, if people are told that their “contrast is too low”, they might not search for it in color.

> "Layout" and "Structure" can be merged

Layout is more for the visual aspects, where structure goes more into the coding aspects of WCAG. I think the tool benefits from both terms being separated.

> "Headings" seem to be repeat of "Layout", "Structure" and "Navigation"

Headings only has heading-specific SCs in it. There is an overlap with the other categories but I’d like to call out headings as a special case and make it clearly visible.

> "Clarification" could be "Content" since clarification is a bit obscure without context

Done.

> "Consistency" and "Compatibility" are also obscure labels without context

I put the two of the SCs in Consistency and added them to layout: 
- 3.2.3 Consistent Navigation
- 3.2.4 Consistent Identification

Additionally I added the SCs above and 3.2.5 Change on Request to structure.

I’m unclear on what to do with compatibility.

**Comment by yatil** [comment]
Two **resolutions** from the [October 16th EOWG meeting](https://www.w3.org/WAI/EO/wiki/EOWG_Meetings_2015#16_October_2015_Teleconference):
- Retain the term "compatibility" until and unless someone has a viable (brilliant) alternative before publication if the QuickRef.
- Explore the development of the functionality of introducing activities filters dependent on the creation of a workable taxonomy.

**Comment by davidberman** [comment]
+1
