### ISSUE TITLE
Draw more attention to the main content area when the content changes

### ISSUE THREAD

**Issue by yatil** [w3c/wai-wcag-quickref#36]
Brought up by @nitedog on Tuesday.

**Comment by nitedog** [comment]
To clarify my comment: I wonder if more clarity is needed on what changes on the page when things are selected. For example, when a tag is selected, which success criteria are activated/deactivated? This could be address through one or more approaches including:
- Improving the feedback in the status section (eg to show which SCs are activated rather than which tags are unselected) -- this feedback could hidden by default but presentable through a "show details" or such function within the status section
- Adding meta-data to the actual tags - for example by using "info-icons" that show which SCs are associated with each tag, or show this information when the tag is hovered/activated, so that people can easily identify what is hidden behind and individual tag before selecting it
- Working on making the tag names even more self-explanatory, or link to a page where the tags are listed together with the associated SCs

**Comment by yatil** [comment]
It was requested that most of the information on the right side stays where it is, which means that not much is changing. I would have preferred that SC vanish that are are not tagged with the current tag.

On the other hand I think users expect the view to change and they will quickly learn how it works.

Regarding your approaches:

> Improving the feedback in the status section (eg to show which SCs are activated rather than which tags are unselected) -- this feedback could hidden by default but presentable through a "show details" or such function within the status section

That would make the status section even more unwieldily than it currently is and renders it useless, imho. Also having a sticky bar with a popup or something sounds like an implementation nightmare, especially as we want to have ALL the information in there.

> Adding meta-data to the actual tags - for example by using "info-icons" that show which SCs are associated with each tag, or show this information when the tag is hovered/activated, so that people can easily identify what is hidden behind and individual tag before selecting it

I doubt that it is helpful to anyone to see the headings of the success criteria when hovering the tag. When the tag is clicked that information is already presented in the right hand column.

> Working on making the tag names even more self-explanatory, or link to a page where the tags are listed together with the associated SCs

I don’t know what you mean with “self-explanatory”. Most tags are simple (images, audio, video) or describe a concept of WCAG (consistency, navigation). Please provide more concrete examples of what you mean in issue #28.

Of course we can have another page that lists the success criteria by tag, but I wonder what the benefit is as the current tool can show the content for two tags as well.

**Comment by yatil** [comment]
I have changed how the filtered Success Criteria are displayed. They are now hidden completely, instead there is a list of hidden SCs on the bottom of the list of relevant SCs.
