### ISSUE TITLE
Understanding in new tab/window

### ISSUE THREAD

**Issue by iadawn** [w3c/wai-wcag-quickref#44]
Why open Understanding in a new tab and nothing else?

Actually, just noticed that all techniques are set to open in a new tab/window but the icon isn't showing.

Which makes the issue broader: why open everything in a new tab? Users can make that choice themselves.

**Comment by yatil** [comment]
Point taken on the icon, the techniques should have them as well. The reason for opening in a new tab/window is that I don’t want people to lose their position in the document. I agree that many users can make that choice themselves, but I think here having the information in a separate tab is increasing the usefulness of the tool.

**Comment by iadawn** [comment]
I can see the rationale, I just have a visceral dislike of 'open in new window' functionality. In many usability testing sessions I have seen this functionality cause more problems than it solves.

Using Firefox, if I visit a new document and then use the back button to return to the Quick Ref, the only thing that does not persist is the state of the Show Techniques expand/collapse.

**Comment by yatil** [comment]
The links now don’t open in new windows anymore, I have added the icon to the techniques links as well to give a hint that those links are external.

**Comment by iadawn** [comment]
👍🏻

**Comment by davidberman** [comment]
As discussed in our meeting this past Friday, opening in a new window is often appropriate when it is more than likely that, after drilling down, the user is likely to want to go back to the main path they were on (or the experience designer wants them to be able to do so). Typically this comes down to the nature of the task: if they are searching for the answer to a specific question, and so they will be done once they find, then replacing the window makes sense. However in an educational tool like the one we are building, where we expect them to return again and again to our main path, then it is disruptive to have to rediscover the main path. All that to say, that I prefer we open a new tab/window in situations likely these.

**Comment by mitchellevan** [comment]
If these links simply navigate, and don't open a new window, then the icons should be removed.

Here is my experience and analysis.
- When I first saw the icon, my initial expectation was that an "Understanding..." link would open a new browser window or tab. But after trying it, I discovered that it simply navigates away from the page. Instead of "giving me a hint that those links are external", it gave me a negative experience, when I expected a new window but instead I lost my exact place in the page.
- Looking around a bit, I see strong evidence that I won't be alone in this experience of the icons. Compare: https://www.google.com/search?q=new+window+icon 
- I am not aware of any globally recognizable way of indicating that a link simply navigates, other than very traditional visual treatment of links e.g. underlines.
- Hence, my recommendation is to remove these confusing icons.
