### ISSUE TITLE
The banner area takes up a considerable amount of vertical area at 1024x768 and 800x600 

### ISSUE THREAD

**Issue by mraccess77** [w3c/wai-wcag-quickref#57]
The banner area is always visible and takes up considerable area and is always on-screen with no way to collapse/hide or scroll it out of view.

**Comment by mraccess77** [comment]
Also when zooming in to 200% on the desktop the site goes into responsive mode and the banner takes up a lot of vertical real estate at other resolutions.

When I view on my iPhone6 the banner scrolls out of view and works as you would expect.  So perhaps this could be solved by adjusting the break points to put a 800x600 users into the same view that an iPhone user would see?

**Comment by yatil** [comment]
Thanks for the feedback Jonathan, I will make adjustments to the breakpoints.

**Comment by mitchellevan** [comment]
I've experienced similar issues, in this configuration:
- Physical screen 1366 by 768 pixels
- Chrome 46 on ChromeOS
- I change my zoom level, then refresh the page.

Experience:
At 175% zoom, with a typical filter, I can read only 2-3 lines of text in the scrollable main content area.
At 200% zoom, the experience gets much better, because the header is no longer in a fixed position (responsive design).

I recommend a very minimal fixed header, containing nothing but the "Show Sidebar" link. None of the other header content is important enough that I want to see it constantly.

**Comment by yatil** [comment]
Hi @mraccess77 and @mitchellevan,

I have changed how the header works, the banner area is now scrolling out of view.

Eric

**Comment by mraccess77** [comment]
This did help for the desktop -  thank you!!!  On my iPhone when I zoom in the bar still takes up a lot of room -- but I'm not sure what zoom level I'm at -- so it's hard to tell at what zoom level the screen becomes unusable and the top bar takes up the bulk of the screen.  Safari does not show the zoom level.
