### ISSUE TITLE
Hide this information button label

### ISSUE THREAD

**Issue by kwahlbin** [w3c/wai-wcag-quickref#59]
Low Priority:  Change the button text "Hide this information" to "Hide Section - About this Quick Reference" or something similar to make it apparent that what you are hiding is the about section.

**Comment by yatil** [comment]
Good suggestion, thank you!

**Comment by slhenry** [comment]
I'm not keen on "Quick Reference" in the button, especially not upper case.

Also, the "?" icon makes me think I'm going to open a big, separate Help page. I think that will deter people from clicking on it -- and we *want* them to.

How about labeling it:
<blockquote>
Show About & How to Use
</blockquote>
and
<blockquote>
Hide About & How to Use
</blockquote>

And changing the icons to arrows -- like the Show/Hide for the sidebar -- although maybe pointing up & down instead of right & left.

**Comment by shawna-slh** [comment]
I'm not keen on "Quick Reference" in the button, especially not upper case.

Also, the "?" icon makes me think I'm going to open a big, separate Help page. I think that will deter people from clicking on it -- and we _want_ them to.

How about labeling it:

<blockquote>
Show About & How to Use
</blockquote>

and

<blockquote>
Hide About & How to Use
</blockquote>

And changing the icons to arrows -- like the Show/Hide for the sidebar -- although maybe pointing up & down instead of right & left.

**Comment by yatil** [comment]
Changed this to your suggestion, @slhenry. I like the simplicity.
