### ISSUE TITLE
Links to the normative Glossary have been omitted

### ISSUE THREAD

**Issue by mitchellevan** [w3c/wai-wcag-quickref#82]
I realize this is a "supporting document" and therefore not normative. However, the old "How to Meet" document had cross-links to the normative "Appendix A: Glossary", while the new version does not have these links, nor does it indicate in any other way that these terms have specific technical definitions in the context of WCAG 2.0.

A key feature of the new "How to Meet" document is to make it easy to share a specific success criterion. So if these cross-links are left out, it will be quite noticeable.

**Comment by yatil** [comment]
Hi @mitchellevan,

thanks for your feedback. We purposefully decided against including links to the glossary to reduce visual (and auditory) complication. Each success criterion contains a link to the Understanding document where the full spec, including links to glossary terms, is shown.

[This issue was discussed in the meeting on Dec 4th, 2015.](http://www.w3.org/2015/12/04-eo-minutes.html#item05)

Best, Eric
